### ISSUE TITLE
预测自己的采集的语音

### ISSUE THREAD

**Issue by sundyll** [yeyupiaoling/VoiceprintRecognition-Pytorch#1]
你好，请问预测自己采集的语音时，需要做什么预处理吗，现在直接用模型预测自己采集的语音时，效果不好

**Comment by yeyupiaoling** [comment]
用这个程序效果不好吗？https://github.com/yeyupiaoling/VoiceprintRecognition-Pytorch/blob/master/infer_recognition.py

**Comment by yeyupiaoling** [comment]
你看这个视频：https://www.bilibili.com/video/BV1e44y117rJ

**Comment by sundyll** [comment]
> 用这个程序效果不好吗？https://github.com/yeyupiaoling/VoiceprintRecognition-Pytorch/blob/master/infer_recognition.py

用的infer_contrast.py，采集了我自己的两段语音比较，得分0.4几

**Comment by sundyll** [comment]
> > 用这个程序效果不好吗？https://github.com/yeyupiaoling/VoiceprintRecognition-Pytorch/blob/master/infer_recognition.py
> 
> 用的infer_contrast.py，采集了我自己的两段语音比较，得分0.4几

刚才我试着把我用手机采集下来的wav语音，先转了一下mp3，再去做识别，就好一些了，两段对比得分得到0.67了，是要做什么预处理吗，降噪、去静音，再去预测？
