### ISSUE TITLE
关于声音输入的问题

### ISSUE THREAD

**Issue by ZhengWenH** [yeyupiaoling/VoiceprintRecognition-Pytorch#14]
有几个地方想请教下您：
1. 对声音拼接随机取反这个操作的作用是什么？
2. 我看了下数据集中，最长的声音11秒多，最短的1秒多，算法中都是随机截取一段2.6秒长的部分，对于较长的输入，利用率是否过低？
3. 能不能通过让STFT窗口长度和步长自适应输入，从而让STFT输出的维度相同

**Comment by yeyupiaoling** [comment]
那个翻转类似图片翻转，主要是增加数据的长度。

网络模型需要这个长度的话，你只能裁剪了。
不可以。
