### ISSUE TITLE
about load audio problem

### ISSUE THREAD

**Issue by sloan96** [yeyupiaoling/VoiceprintRecognition-Pytorch#16]
hello, I have two questions.
1. why choose librosa.stft()  and magphase() as input features? why not MFCC?
2. why choose '257' as spectrum length? I want to train voxceleb dataset, can you give me some advice on data processing and parameter selection?
Looking forward to reply.

**Comment by yeyupiaoling** [comment]
1、MFCC is not suitable for voiceprint recognition, MFCC is more suitable for speech recognition

2、Refer to this document：
https://github.com/yeyupiaoling/VoiceprintRecognition-Pytorch#%E5%88%9B%E5%BB%BA%E6%95%B0%E6%8D%AE

**Comment by sloan96** [comment]
> 1、MFCC is not suitable for voiceprint recognition, MFCC is more suitable for speech recognition
> 
> 2、Refer to this document： https://github.com/yeyupiaoling/VoiceprintRecognition-Pytorch#%E5%88%9B%E5%BB%BA%E6%95%B0%E6%8D%AE

Thanks for the reply. I'm still a little confused.
1. Have you tried other audio features? such as fbank or other...how is the effect?
2. Multiple vocals appear in my data, even overlapping, any suggestion?
3. In voiceprint comparison, if the test data duration is too long, I need to split the audio frame, any suggestion to save time?
In addition, I give some advice on your code. Use multiprocess and FFmpeg on data processing(mp3 to wav), then processing time reduced from 30 hours to 3 hours.
I am new to voiceprint recognition and looking forward to replying.

**Comment by yeyupiaoling** [comment]
1、I have not used any other preprocessing methods, but there is not only one effective preprocessing method .
2、Since this project is voiceprint recognition, sound separation may need to be considered in this case.
3、The default in forecasting is to crop only the first part.  Or you can crop multiple lengths of the same length and then do it all at once, making a tradeoff.

Thank you for your suggestion.

Can you use Chinese? Translation software results do not know whether normal expression.

**Comment by sloan96** [comment]
> 1、I have not used any other preprocessing methods, but there is not only one effective preprocessing method . 2、Since this project is voiceprint recognition, sound separation may need to be considered in this case. 3、The default in forecasting is to crop only the first part. Or you can crop multiple lengths of the same length and then do it all at once, making a tradeoff.
> 
> Thank you for your suggestion.
> 
> Can you use Chinese? Translation software results do not know whether normal expression.

thank you. I get it.
