### ISSUE TITLE
WAV sound durations is always 4 seconds?

### ISSUE THREAD

**Issue by xellDart** [yeyupiaoling/VoiceprintRecognition-Pytorch#17]
Hi, thanks for your work, I have one question, corpus database is always 4 seconds, can I use wav samples with different duration?

I have same samples with 4, 5 and 6 seconds of duration...

**Comment by yeyupiaoling** [comment]
You can. You can understand this parameter.

https://github.com/yeyupiaoling/VoiceprintRecognition-Pytorch/blob/e68069ae427d0f0bc5b39ae86ea567a97e47483e/train.py#L31
