### ISSUE TITLE
推理预测错误

### ISSUE THREAD

**Issue by 827379852** [yeyupiaoling/VoiceprintRecognition-Pytorch#28]
您好 我请问一下，在使用ecapa_tdnn，模型推理时候，特征提取选择spectrogram，但是得到的特征只是一个值是什么原因呢，并且对比任意两个音频相似度都是1。使用的是下面的预训练模型。
![a66545f1c2a39f8ea6527f6bd6e17b2](https://user-images.githubusercontent.com/79695576/172316183-2c661f29-41cc-42fd-b4e3-78afd2583af0.png)
![715806fd505e065ac0ba64c5f0bd3e4](https://user-images.githubusercontent.com/79695576/172316310-13b936e1-2991-45b2-a84e-eecf7f10e98a.png)

**Comment by yeyupiaoling** [comment]
特征不止一个值的，你打印错误了吧。

>且对比任意两个音频相似度都是1

可能你没有正确加载模型，你试试infer_path这个程序先
