### ISSUE TITLE
采样率

### ISSUE THREAD

**Issue by hans208** [yeyupiaoling/VoiceprintRecognition-Pytorch#29]
训练数据和模型的采样率16k。我要推理的数据是电话语音，采样率是8k，我重采样到16k后，发现声纹对比效果很差，不论怎样的两段语音，声纹相似度都比较大，男女对比的相似度有的都能达到0.4。
请问会是什么原因呢？

**Comment by yeyupiaoling** [comment]
这个有一定影响，你有试过16K的吗？有没有正常16K的。

**Comment by hans208** [comment]
有试过正常的16k，效果很好。请问这种16k训练的模型， 推断时是8k的电话语音，效果不好的原因及解决方法？
我的猜测：
原因：1. 设备问题，手机、麦克风vs电话，导致信道差异
           2. 16khzvs8khz，将8khz提升到16khz 无频谱信息的增加
 解决方法：
1. 换数据（行不通，网上没找到原生的8khz的电话数据集）
2. 将16k的训练数据下采样到8k训练

另外我用您的模型测了一下您提供的audio文件夹下的四个音频，将16khz降采样到8khz再上采样到16khz，声纹对比时相似度都提升了0.2。

**Comment by hans208** [comment]
有试过正常的16k，效果很好。请问这种16k训练的模型， 推断时是8k的电话语音，效果不好的原因及解决方法？
我的猜测：
    原因：
        1. 设备问题，手机、麦克风vs电话，导致信道差异
        2. 16khzvs8khz，将8khz提升到16khz 无频谱信息的增加
    解决方法：
        1. 换数据（行不通，网上没找到原生的8khz的电话数据集）
        2. 将16k的训练数据下采样到8k训练

另外我用您的模型测了一下您提供的audio文件夹下的四个音频，将16khz降采样到8khz再上采样到16khz，声纹对比时相似度都提升了0.2。

**Comment by hans208** [comment]
有试过正常的16k，效果很好。请问这种16k训练的模型， 推断时是8k的电话语音，效果不好的原因及解决方法？
我能想到的原因和解决方法，大大看下，麻烦给个意见
原因：
1. 设备问题，手机、麦克风vs电话，导致信道差异
2. 16khzvs8khz，将8khz提升到16khz 无频谱信息的增加
解决方法：
1. 换数据（行不通，网上没找到原生的8khz的电话数据集）
2. 将16k的训练数据下采样到8k训练

另外我用您的模型测了一下您提供的audio文件夹下的四个音频，将16khz降采样到8khz再上采样到16khz，声纹对比时相似度都提升了0.2。

**Comment by hans208** [comment]
有试过正常的16k，效果很好。请问这种16k训练的模型， 推断时是8k的电话语音，效果不好的原因及解决方法？
我能想到的原因和解决方法，大大看下，麻烦给个意见
原因：
    1. 设备问题，手机、麦克风vs电话，导致信道差异
    2. 16khzvs8khz，将8khz提升到16khz 无频谱信息的增加
解决方法：
    1. 换数据（行不通，网上没找到原生的8khz的电话数据集）
    2. 将16k的训练数据下采样到8k训练
另外我用您的模型测了一下您提供的audio文件夹下的四个音频，将16khz降采样到8khz再上采样到16khz，声纹对比时相似度都提升了0.2。

**Comment by yeyupiaoling** [comment]
你的想法很好。直接将音频下采样，然后训练。另外数据集里面大部分都是很安静的环境。建议在数据加强里面添加噪声增强。
