### ISSUE TITLE
博主大大你好，有关特征值和对角余弦问题

### ISSUE THREAD

**Issue by yy835055664** [yeyupiaoling/VoiceprintRecognition-Pytorch#30]
![$QQD2S 0H}2~JGFOVQK6B37](https://user-images.githubusercontent.com/57432458/177755646-549fad3c-c5b0-4fb9-8702-8302d6a970b5.png)
![$D9R R2957OT180$PI)3KC5](https://user-images.githubusercontent.com/57432458/177755652-61e3de98-4d47-4199-9c93-672b38ae9da4.png)
博主你好，目前出现了这样一个问题：运行infer_recognition.py时实验最终结果进行声纹识别时无论说话与否都对应的是第一个注册者，开始怀疑模型调用的问题，但是运行infer_contrast.py的时候结果正常，所以排除模型调用及路径问题，又使用pycharm进行分布调试，在代码进行到声纹识别的步骤时，最终dist值没有计算正确，直接显示了1，出现问题的代码如下
feature = infer(path)[0]
    for i, person_f in enumerate(person_feature):
        dist = np.dot(feature, person_f) / (np.linalg.norm(feature) * np.linalg.norm(person_f))
所以怀疑是否是特征提取的问题或者是dist值计算出错了，请问博主具体的问题出现在哪以及如何去解决，万分感谢！

**Comment by yeyupiaoling** [comment]
你用的是最新代码吗？对比那个有没有正常？

**Comment by yy835055664** [comment]
> 你用的是最新代码吗？对比那个有没有正常？

博主你好，我用的是旧版本的，我们刚调试解决了一部分问题，但是出现了这样的新问题：无论说话与否都会识别一个说话人，没有打印出音频库没有该用户的语音这行代码，而且识别准确率比较低，麻烦博主，谢谢。

**Comment by yeyupiaoling** [comment]
拉取最新代码可以解决，你这个是什么时候拉取的？
