### ISSUE TITLE
训练问题咨询

### ISSUE THREAD

**Issue by mjwSilence** [yeyupiaoling/VoiceprintRecognition-Pytorch#31]
hello，我换了ubuntu机器在训练模型，目前没有异常，想问下时间的问题：
按照每条日志间隔的时间计算，执行完大概需要40+小时，这个没问题，但我想问下，Train epoch [0/30]，时表示这种40+小时的训练需要进行三十次吗？还是说有别的意思？
![image](https://user-images.githubusercontent.com/25688415/180135695-ff295f62-2e21-4138-a552-c59ec33f81bb.png)

Thanks.

**Comment by yeyupiaoling** [comment]
全部训练剩余时间。

**Comment by mjwSilence** [comment]
了解

**Comment by mjwSilence** [comment]
hello, 又是我，哈哈哈
这次想问下你14小时训练完成用的是什么配置，我用的ubuntu   gtx 1660，不过现在训练了有五六天了，进度只到了 [3/30]，看上去遥遥无期，是不是我的配置不行？

**Comment by yeyupiaoling** [comment]
双2080ti跑满

**Comment by mjwSilence** [comment]
那还是差距有点大，了解了

**Comment by mjwSilence** [comment]
请教下，模型训练有可能只拿其中一部分数据来做训练吗？效果差点没关系，我做个demo

**Comment by mjwSilence** [comment]
或者减少训练的轮数可行？30轮是不是为了加强模型准确率？一轮是不是也可以？

**Comment by yeyupiaoling** [comment]
可以的，如果你不在乎准确率，可以只训练一轮

**Comment by mjwSilence** [comment]
了解，3Q

**Comment by mjwSilence** [comment]
hello，叨扰了，请教个问题，我看代码，如果训练到一半就停了程序，是不会保存模型的对吗？
像是在这个地方直接停掉程序：
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/25688415/182982948-0d25b31b-9855-457a-a7b6-d7f5e979c17c.png">

**Comment by yeyupiaoling** [comment]
每一轮才会保存一次模型

**Comment by mjwSilence** [comment]
那就是说我这里如果停掉，实际上还是能得到一个训练了七轮的模型？

**Comment by yeyupiaoling** [comment]
是的

**Comment by mjwSilence** [comment]
了解，感谢

**Comment by mjwSilence** [comment]
hello，感谢，我的训练结束了，9轮，评估准确率99%+
但还是有一个问题请教，我在测试声纹识别功能的时候，同一个人说同一句话，相似度只有85%，同一个人说不同的话，相似度只有76%，这两个结果都被判断是同一个人，请问这个相似度已经算是很高的匹配率了吗？还是因为我只训练了9轮导致的问题？
![image](https://user-images.githubusercontent.com/25688415/183844272-e005dc43-868d-4e74-8336-5ed3bdb239df.png)

**Comment by mjwSilence** [comment]
是不是阈值是这个0.58？这个值以上就判断是同一个人这样吗？
<img width="358" alt="image" src="https://user-images.githubusercontent.com/25688415/183844979-7e413d30-dfa1-4797-8623-227d18c18fda.png">

**Comment by yeyupiaoling** [comment]
你用全部数据训练模型吗？我一般是0.5.

**Comment by mjwSilence** [comment]
是的，我用的全部数据，0.5是指你的模型阈值是0.5吗？
那你的声纹识别相似度一般在什么数值？比如同一个人同一句话的情况下

**Comment by yeyupiaoling** [comment]
一般是0.5，但也不是绝对，看项目要求严格程度。

**Comment by mjwSilence** [comment]
哦这样，那70%的相似度是不是已经算是比较正常的相似度？85就算很相似了这样吗？

**Comment by yeyupiaoling** [comment]
嗯嗯，你录音的时候要避免静音时间太长

**Comment by mjwSilence** [comment]
OK，3Q
