### ISSUE TITLE
关于测试

### ISSUE THREAD

**Issue by EdenJin20171503024** [yeyupiaoling/VoiceprintRecognition-Pytorch#32]
我发现您的这个项目中训练时，在验证的时候用的时test list，但是在eval的时候也是用的test去测试模型的效果，是不是在train的时候验证的时候用dev集比较好

**Comment by yeyupiaoling** [comment]
只是验证测试时没必要这么分。

**Comment by jzz990415** [comment]
能问一下这个模型的话是有哪篇论文吗，想研究一下

**Comment by yeyupiaoling** [comment]
你搜索下ecapa_tdnn
