### ISSUE TITLE
数据

### ISSUE THREAD

**Issue by jzz990415** [yeyupiaoling/VoiceprintRecognition-Pytorch#33]
我发现我处理完的data总共类别只有2531个类，和你的不一样，可能有一些数据解压的有问题，但是类别的增长并不是连续的，请问这个是删除音频方法的原因吗
<img width="888" alt="image" src="https://user-images.githubusercontent.com/102025844/186327646-dd26c06e-9404-45bb-a57c-357aa4e098b2.png">

**Comment by yeyupiaoling** [comment]
我沒有验证过这个数据集哦，我是根据他的标注数据生成数据列表的。

**Comment by jzz990415** [comment]
我还想问大佬一下，你的label我看是用第几个speaker去编码的，我用其他的数据集的话它带有id标签，我可以直接用id当label吗

**Comment by yeyupiaoling** [comment]
嗯

**Comment by jzz990415** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/102025844/187064064-113c58ad-a24b-49b1-8201-5facdaa5d2e1.png">
请问大佬这里的summary里的98是什么

**Comment by jzz990415** [comment]
<img width="1714" alt="image" src="https://user-images.githubusercontent.com/102025844/187069170-5ac67a86-d4d1-407d-b05c-b9b2bb05b0b9.png">
我在另一个数据集去跑的实验，他train的时候报错了，您能帮我看一下是因为什么吗，这里的label我用的是voxceleb中的id去掉id的数字

**Comment by yeyupiaoling** [comment]
这个有没有设置正确
https://github.com/yeyupiaoling/VoiceprintRecognition-Pytorch/blob/3797c9659837700b7cdb96e0fe9e27ea47b5fbcf/train.py#L32
