### ISSUE TITLE
关于测试

### ISSUE THREAD

**Issue by jzz990415** [yeyupiaoling/VoiceprintRecognition-Pytorch#34]
您好，我想知道您的list放进dataloader或者是您自己的customdataset的时候有打乱顺序吗

**Comment by yeyupiaoling** [comment]
自动打乱的
https://github.com/yeyupiaoling/VoiceprintRecognition-Pytorch/blob/3797c9659837700b7cdb96e0fe9e27ea47b5fbcf/train.py#L96

**Comment by jzz990415** [comment]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/102025844/186869731-bc10211a-8825-4be7-a673-f08f2c6fa90d.png">
在测试的时候应该没有打乱吧，我记得shuffle好像默认是false

**Comment by yeyupiaoling** [comment]
测试不用打乱啊

**Comment by jzz990415** [comment]
好的好的谢谢
