### ISSUE TITLE
这个可以NCNN 部署吗？

### ISSUE THREAD

**Issue by zuowanbushiwo** [yeyupiaoling/VoiceprintRecognition-Pytorch#37]
你好，
       有没有C++的部署方案？谢谢！

**Comment by yeyupiaoling** [comment]
没有， 这个模型不支持导出

**Comment by zuowanbushiwo** [comment]
@yeyupiaoling 
感谢大佬回复，不支持导出是什么意思？不支持 jit trace吗？

**Comment by zuowanbushiwo** [comment]
我是从speech Enhancement 转过来的，上周被要求做一个声纹的C++ demo， 要求能部署，我以前的AEC/NS 都是使用NCNN 部署的。

**Comment by yeyupiaoling** [comment]
我不懂c++

**Comment by zuowanbushiwo** [comment]
大佬，你上面说的 不能导出是什么意思？谢谢！

**Comment by aso538** [comment]
可以通过onnx部署c++应该 我转成onnxruntime的推理框架了 但是是python版本的 c++的前后处理代码得自己写

**Comment by fmbao** [comment]
> 可以通过onnx部署c++应该 我转成onnxruntime的推理框架了 但是是python版本的 c++的前后处理代码得自己写

onnx 只导出ECAPA-TDNN模型就行吗？SpeakerIdentification 部分需要导出嘛？

**Comment by shenjun1994** [comment]
> 可以通过onnx部署c++应该 我转成onnxruntime的推理框架了 但是是python版本的 c++的前后处理代码得自己写

大佬，转onnx的代码和onnx的推理代码可以分享一下吗？
