### ISSUE TITLE
数据集规模

### ISSUE THREAD

**Issue by wang304381190** [yeyupiaoling/VoiceprintRecognition-Pytorch#38]
老师您好，请问超大的数据集数据量是多大呀，用了多少小时的数据，我从网上找了差不多所有的带有说话人信息的中文语音数据集，包括cn-celeb、aishell3、4和阿里开源的数据集，大约有2000+小时，想用您的模型训练一下对比一下效果

**Comment by zuowanbushiwo** [comment]
@wang304381190  请问阿里开源的数据集 在哪里？ 最近也在找数据集。

**Comment by wang304381190** [comment]
同学你好，我晚上或者明早发给你网址，或者你可以自己找一下，在openslr上



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月18日(周三) 上午10:36
收件人: ***@***.***&gt;;
抄送: "Shining ***@***.******@***.***&gt;;
主题: Re: [yeyupiaoling/VoiceprintRecognition-Pytorch] 数据集规模 (Issue #38)




 
@wang304381190  请问阿里开源的数据集 在哪里？ 最近也在找数据集。

**Comment by zuowanbushiwo** [comment]
好的，谢谢！刚刚通过你提供的信息搜索了一下是这个吗？
![image](https://user-images.githubusercontent.com/3354428/213075516-c4aa3c50-c2b2-4329-a12e-9d459f8113cf.png)

**Comment by wang304381190** [comment]
对的，是这个



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月18日(周三) 中午11:20
收件人: ***@***.***&gt;;
抄送: "Shining ***@***.******@***.***&gt;;
主题: Re: [yeyupiaoling/VoiceprintRecognition-Pytorch] 数据集规模 (Issue #38)




 
好的，谢谢！刚刚通过你提供的信息搜索了一下是这个吗？
