### ISSUE TITLE
多卡训练错误

### ISSUE THREAD

**Issue by BrightXiaoHan** [yeyupiaoling/VoiceprintRecognition-Pytorch#41]
我已经更新到develop分支最新版本，但是多卡训练会报错，单卡训练没问题
```
CUDA_VISIBLE_DEVICES=0,1 torchrun --standalone --nnodes=1 --nproc_per_node=2 train.py
```

<img width="1455" alt="截屏2023-03-09 00 30 59" src="https://user-images.githubusercontent.com/25839309/223772137-127ae2b5-6cd8-44f7-9390-c2164be2bbc9.png">

**Comment by yeyupiaoling** [comment]
我也看不出是什么原因
