### ISSUE TITLE
找不到dataset/zhvoice/text/infodata.json文件

### ISSUE THREAD

**Issue by Downupanddownup** [yeyupiaoling/VoiceprintRecognition-Pytorch#42]
作者你好，在执行 python create_data.py 的时候，找不到dataset/zhvoice/text/infodata.json文件，需要怎么做呢？

**Comment by eeric** [comment]
下载数据库zhvoice，百度网盘地址：https://pan.baidu.com/s/1uHXE2WIt0kdm_dPSej-TtA，提取码: i5b3
它里面有

**Comment by Downupanddownup** [comment]
好的
