### ISSUE TITLE
博主，您好

### ISSUE THREAD

**Issue by wxy0505** [yeyupiaoling/VoiceprintRecognition-Pytorch#46]
您好，我想问下那个训练的图train/loss这个图的横坐标代表的什么？

**Comment by yeyupiaoling** [comment]
步数。

**Comment by wxy0505** [comment]
博主，那fpr和tpr这两个参数是代表了什么指标？

**Comment by wxy0505** [comment]
还有那个模型的效果，按理论来说模型Ecapa-TDNN的效果是不是应该比模型ResnetSE的效果要更好些？

**Comment by wxy0505** [comment]
因为确实没找到有关这方面的解答，所以才来请教，希望能得到您的答复，谢谢。

**Comment by yeyupiaoling** [comment]
>还有那个模型的效果，按理论来说模型Ecapa-TDNN的效果是不是应该比模型ResnetSE的效果要更好些？

是的，本项目Ecapa-TDNN效果是最好的。
