### ISSUE TITLE
运行文档里面的infer_contrast.py代码，两个不同的人的语音对比都是识别为同一人。

### ISSUE THREAD

**Issue by heyun913** [yeyupiaoling/VoiceprintRecognition-Pytorch#50]
直接在CSDN下载的大佬你上传的已经训练好的modle.pth，然后代码什么都没改，运行测试代码发现效果很差，不同人的两段语音识别n次结果都是识别为同一个人。

**Comment by yeyupiaoling** [comment]
你下载的是哪个，有没有在对应的分支上使用？

**Comment by heyun913** [comment]
下的pth是这个连接https://download.csdn.net/download/qq_33200967/85270001 ，然后代码是release1.0的（直接从readme文档转到这个csdn页面的）。你的infer_contrast.py比较a.1wav和b_2.wav结果是-0.0956....，我的基本在0.9以上。大佬看我操作有问题没

**Comment by yeyupiaoling** [comment]
这样下载应该版本不会错乱才对。你是不是从第三方比如淘宝那些去下载的？

**Comment by heyun913** [comment]
没有，代码就是github上的，pth模型就是9.9元那个
&nbsp;


何韵
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月5日(星期二) 晚上6:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yeyupiaoling/VoiceprintRecognition-Pytorch] 运行文档里面的infer_contrast.py代码，两个不同的人的语音对比都是识别为同一人。 (Issue #50)





 
这样下载应该版本不会错乱才对。你是不是从第三方比如淘宝那些去下载的？

**Comment by heyun913** [comment]
我下的pth模型，预处理方法是spectrogram，难道测试代码哪里需要改吗？

**Comment by heyun913** [comment]
已经好了，之前特征提取方式我没有改，抱歉，才学习，不是很懂。
另外大佬两个群都满了，还有其他群吗？

**Comment by yeyupiaoling** [comment]
没有其他群了。
