### ISSUE TITLE
如何修改损失函数 

### ISSUE THREAD

**Issue by zxj11zxj11zxj11** [yeyupiaoling/VoiceprintRecognition-Pytorch#54]
尊敬的作者您好，我将AAMloss改为CEloss之后代码报错如下图，将下面的损失函数参数删除掉也仍旧报错，希望能得到您的帮助。
![M{8H(3R`2BBG S}TX9HJVB](https://github.com/yeyupiaoling/VoiceprintRecognition-Pytorch/assets/127805303/04645eae-4bd4-41d6-9b17-07981a4dca2d)

**Comment by yeyupiaoling** [comment]
没改之前能够跑起来吗？你那个是打印模型的时候报的错误，Loss应该不影响的。

**Comment by yeyupiaoling** [comment]
我这边运行没有问题
