### ISSUE TITLE
请问怎么得到这个模型的EER和minDCF值。

### ISSUE THREAD

**Issue by ForeAction** [yeyupiaoling/VoiceprintRecognition-Pytorch#57]
请问我怎么可以得到这个项目中ECAPA-TDNN模型的EER和minDCF？我用这个项目的create_data.py处理数据之后，使用train.py训练模型，最后修改eval.py文件得到的EER和minDCF是有问题的，显示负样本为零。

**Comment by yeyupiaoling** [comment]
你看看你的数据是不是太少，你的测试机是下载的，还是自己做的？
