### ISSUE TITLE
FileNotFoundError error: run python create_data.py 

### ISSUE THREAD

**Issue by lonngxiang** [yeyupiaoling/VoiceprintRecognition-Pytorch#59]
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/zhvoice/text/infodata.json'

**Comment by yeyupiaoling** [comment]
你没有下载这个数据集呀？

**Comment by lonngxiang** [comment]
> 你没有下载这个数据集呀？

下载了，放到代码这一级目录的；看需要怎么处理吗，教程好像这块细节也没写

![image](https://github.com/yeyupiaoling/VoiceprintRecognition-Pytorch/assets/40717349/f5db7149-9c67-4a34-8f09-d16517ddfe7e)

**Comment by yeyupiaoling** [comment]
看文档啊，文档写的很清楚了。放在dataset里面，然后全部解压。

**Comment by yeyupiaoling** [comment]
你用的是0.3版本的分支吧？

**Comment by lonngxiang** [comment]
> 看文档啊，文档写的很清楚了。放在dataset里面，然后全部解压。

麻烦文档在哪里呢，看readme里写的不够详细
![image](https://github.com/yeyupiaoling/VoiceprintRecognition-Pytorch/assets/40717349/348f05b5-a70e-44d6-8027-f7196246ff9e)

**Comment by lonngxiang** [comment]
> 你用的是0.3版本的分支吧？

好像再去看了下不是最新版本的，是在别处看到的项目链接，打开看是下载zhvoice来做；没特别注意最新已经改版哈
