### ISSUE TITLE
关于模型微调的数据量

### ISSUE THREAD

**Issue by xxchauncey** [yeyupiaoling/VoiceprintRecognition-Pytorch#60]
在测试最大数据集训练的cam++模型之后，发现效果在目前自己的实验场景下比较一般，需要再进行优化，请问大概需要多少的数据量进行模型微调可以得到比较不错的结果？

**Comment by yeyupiaoling** [comment]
声纹识别模型不能直接微调，因为这样会打乱之前训练好的说话人的ID。

**Comment by xxchauncey** [comment]
> 声纹识别模型不能直接微调，因为这样会打乱之前训练好的说话人的ID。

是否可以扩充说话人ID并且扩充模型最后的linear层来实现微调？类似于NLP中扩充词表的做法。

另外我发现CAM++模型中，“更大数据集”版本存了classifier的weight，但是“超大数据集“版本却没有存。

**Comment by yeyupiaoling** [comment]
应当是可以的

**Comment by xxchauncey** [comment]
你好，注意到repo更新了增量学习，但有一点疑惑：说明里面指出直接微调模型可能导致不可用，但是表格中的指标直接微调要好于增量学习，甚至优于from scratch训练，这里如何理解？

**Comment by yeyupiaoling** [comment]
>说明里面指出直接微调模型可能导致不可用，但是表格中的指标直接微调要好于增量学习，甚至优于from scratch训练

那应该是的数据大的原因，实际使用情况，通常微调的数据都很小，这种情况直接微调的模型基本就无用了
