### ISSUE TITLE
speakers数量太大，导致最后的全连接层参数量巨大，然后就CUDA out of memory了

### ISSUE THREAD

**Issue by quliulangle** [yeyupiaoling/VoiceprintRecognition-Pytorch#63]
speakers得有100万，batchsize已经设置的很小了，还是出错

**Comment by yeyupiaoling** [comment]
@quliulangle 这么大的说话人吗？有没有把speed_perturb_3_class设置为False

**Comment by yeyupiaoling** [comment]
在配置文件里面设置的。打印的模型结构里面，最后的分类层多少参数？

**Comment by quliulangle** [comment]
![image](https://github.com/yeyupiaoling/VoiceprintRecognition-Pytorch/assets/36911538/2f7c3712-9e13-48e8-bfcd-a491a30d4bc2)

**Comment by yeyupiaoling** [comment]
是有点离谱哦，显存多大，还不够？

**Comment by yeyupiaoling** [comment]
@quliulangle speed_perturb_3_class设置为False
