### ISSUE TITLE
GPU利用率为0

### ISSUE THREAD

**Issue by ZXHe23** [yeyupiaoling/VoiceprintRecognition-Pytorch#66]
安装了GPU版本的Pytorch，并且torch.cuda.is_available()返回为True，使用train.py时打印设备print(trainer.device)为cuda，但资源管理器中GPU使用率一直为0

代码版本是release-0.x，没有将mp3转为wav，是因为mp3读取太慢了吗

**Comment by yeyupiaoling** [comment]
最新版本的soundfile支持mp3，这个读取不会很慢。你看看有没有显存占用，如果占用就是正常使用GPU
