### ISSUE TITLE
I think there is a way to reduce the amount of ram used when using cosine_similarity function

### ISSUE THREAD

**Issue by PigBruhs** [yeyupiaoling/VoiceprintRecognition-Pytorch#68]
- **Original Code:**
![b76e46ab3f42436885c9d1a7898ed64](https://github.com/user-attachments/assets/bf45edc5-7be9-4965-8c6d-677a6034c75d)
- **Test Code:**

```python
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

a = np.random.randn(1524,192)
b = np.random.randn(4864,192)
c = np.expand_dims(b[0], 0).repeat(len(a),axis=0)
d = np.expand_dims(b[0],0)


score = cosine_similarity(d,a)
score_test = cosine_similarity(c,a)

print(score.shape)
print(score_test.shape)
print(len(score_test.tolist()))

print(score.tolist()[0])
print(score_test.tolist()[0])
```

Test code output:
![5ceddfe2bcf9bda8dd45fd710046764](https://github.com/user-attachments/assets/ab4fd546-a5aa-44ec-934b-1333bcd8cfd4)

- If eroll_features.shape() = (n,m),trials_features.shape() = (k,m),then the score of the original code would be a matrix of (n,n) before executing .tolist()[0], taking up a peak ram of n^2 * 8 bytes(FP64). In the test code it would only take up a peak ram of n * 8 bytes
- There is a slight difference between the output of two methods. I'm not sure why, but it shouldn't be affecting greatly on the outcome.

**Comment by yeyupiaoling** [comment]
验证有效
