### ISSUE TITLE
去除噪音干扰

### ISSUE THREAD

**Issue by momohuangsha** [yeyupiaoling/VoiceprintRecognition-Pytorch#7]
非常感谢分享。
由于训练数据是相对安静，噪音很少的环境中生成的。使用训练的模型进行推理时，噪声干扰影响感觉还是比较大的
想请教一下这个问题应该怎样处理。我的想法是训练时把随机随机加入分贝数不同的各种环境噪音。不知道是否有用？或者还要结合降噪的算法吗？
另外：如果多个人同时说话，有没有什么方法能将不同人的声音进行分离，然后在依次进行识别。
还望不吝赐教！
再次感谢

**Comment by yeyupiaoling** [comment]
你在训练集里面加入噪声这是不可取的，应该是在识别的时候把要识别的音频降噪，还有去静音。我之前有加入，但是那个库效果不太好，所以就去掉了。

**Comment by YU-Anthony** [comment]
> 

声音分离是另一个研究方向了，可以浏览一下相关研究
