### ISSUE TITLE
关于infer_recognition_gui.py中的实时识别，会发出如下warning然后出不来结果

### ISSUE THREAD

**Issue by Wangxuelong666** [yeyupiaoling/VoiceprintRecognition-Pytorch#70]
D:\Anaconda\anaconda3\envs\py39\lib\site-packages\soundcard\mediafoundation.py:772: SoundcardRuntimeWarning: data discontinuity in recording
  warnings.warn("data discontinuity in recording", SoundcardRuntimeWarning)

**Comment by pengyuyanllll** [comment]
这个后面怎么解决？
