### ISSUE TITLE
20w+ speakers in training data？ 

### ISSUE THREAD

**Issue by MM-0712** [yeyupiaoling/VoiceprintRecognition-Pytorch#71]
@yeyupiaoling 大佬，有两个问题请教下：
1、文档里写的 20w + 说话人训练集都是开源的吗？
2、20w + 说话人的训练集，是纯中文还是说混合了其他语种数据呢？
感谢回答！

**Comment by yeyupiaoling** [comment]
这个是阿里不开源的一个数据集。只有中文。

**Comment by MM-0712** [comment]
可以提供一下相关资料吗？看看有没有办法跟阿里合作弄下。

**Comment by MM-0712** [comment]
从 3d-speaker 上找到了
