### ISSUE TITLE
create_data出现问题

### ISSUE THREAD

**Issue by feizy** [yeyupiaoling/VoiceprintRecognition-Pytorch#8]
好像是在MP3转wav的时候报错，wav = AudioSegment.from_mp3(audio_path)这步，网上查了半天没找出办法，不知道作者是否知道解决办法，谢谢！
错误代码：
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yeyupiaoling** [comment]
根据提示，应该不是wav = AudioSegment.from_mp3(audio_path)的错误，
应该是在读取json文件的时候出错的，你检查下json文件路径

**Comment by yeyupiaoling** [comment]
这个文件是存在的吗？你有听过这个音频是否正常吗？

**Comment by feizy** [comment]
> 这个文件是存在的吗？你有听过这个音频是否正常吗？

是存在的，就是从数据集里拷贝出来的一个文件。我听过，也没问题。迷茫了。

**Comment by feizy** [comment]
解决了，是ffmpeg没有配置环境变量造成的。
